### ISSUE TITLE
Delete Failed: "Could not delete file"

### ISSUE THREAD

**Issue by immortaleeb** [XDjackieXD/PackUpdate#1]
I sometimes encounter this error because the updater somehow thinks I have an old version of a mod installed, while in actuality I don't.
It then tries to delete a file that does not exist, which causes an exception and stops the whole updating process.

Solution: check if the file exists before deleting it.
Also: It might be nice to not stop the whole updating process, but keep all errors in a list and show them at the end or, alternatively, not launch minecraft after something has gone wrong.

**Comment by XDjackieXD** [comment]
What version of PackUpdate are you using?
The current version (2.0) downloads first and then tries to delete the old one.
It still errors if the deletion failed but it completes the download and shows the error at the end (I should probably make it a warning though as it is not critical most of the time).

**Comment by immortaleeb** [comment]
Apparently the ForgeThis MultiMC instance is running an old version of your updater (1.1). 
I'll update it and let you know if I encounter this issue again.

**Comment by XDjackieXD** [comment]
Ok!
Thank you for reporting (It's better to have a few false positives than people being quiet about bugs ;) )

**Comment by XDjackieXD** [comment]
Should be fixed with latest release.
