### ISSUE TITLE
Comments are broken due to an error in the if statement

### ISSUE THREAD

**Issue by Tylian** [XDjackieXD/PackUpdate#10]
[This line](https://github.com/XDjackieXD/PackUpdate/blob/master/src/at/chaosfield/packupdate/FileManager.java#L157) should be this:

``` java
 if(!(tmp.equals("") || tmp.startsWith("#"))){
```

**Comment by XDjackieXD** [comment]
thanks for pointing that out. I will push a new release tomorrow

**Comment by Tylian** [comment]
No problem, I would have just did a pull request myself but was busy. Sorry. :p
