### ISSUE TITLE
Cleanup removed resource zip

### ISSUE THREAD

**Issue by kotoroshinoto** [XDjackieXD/PackUpdate#13]
if we remove a resources zip (or even change contents in such a way that something gets removed), there should probably be a cleanup, download the zip and check its contents and remove them, etc.

**Comment by XDjackieXD** [comment]
It's pretty hard to do as you'd have to keep track which files belong to a resource zip.
If that's better I could add options to add individual resource files to the pack config. that way it is possible to remove them again.

**Comment by kotoroshinoto** [comment]
perhaps when it is doing the unzip it can track the paths it is writing to in a slightly different manner in the inner pack.config

maybe use "resourceunzipped" type to track the files? you'd have to name the parent resourcezip somehow,.

Might be cleaner to make a second csv to track unzipped_resources

how does it handle the configs?

**Comment by XDjackieXD** [comment]
for configs I'm just deleting the config folder's content

**Comment by darthvader45** [comment]
Just so I know, what the heck is updaterupdater?  Also, could use a wiki to learn how to use it properly (install, etc.)

**Comment by XDjackieXD** [comment]
updaterupdater is a really small jar that updates packupdate from github releases automagically because 90% of the bug reports I got were because of outdated packupdate versions.
updaterupdater is really simple and should rarely need an update.

**Comment by Kilobyte22** [comment]
To bring life back into this issue: This issue is now resolved in the 3.0 rewrite by tracking all installed files for a given component. Release will be soon(tm)
