### ISSUE TITLE
updater nonzero exitcode

### ISSUE THREAD

**Issue by kotoroshinoto** [XDjackieXD/PackUpdate#14]
it appears to have updated everything, but then it gets the message "crashed with exitcode -1073741819.

This is on my friend's machine, on my own this works normally. (she might be on a vpn, would that mess with this software?)

**Comment by XDjackieXD** [comment]
if the VPN is transparent for http(s) it won't make any difference. the Exit code is interesting though as I never throw anything that would cause it. What is their Java version?

**Comment by kotoroshinoto** [comment]
java8 121 x64 JDK i believe.

its a very strange problem. I tested the command on command-line and it is indeed acting like it crashed. (windows pops up its thing about doing a diagnosis on the program that failed in an unusual way).

the weird thing is it finishes its update processing before crashing.

**Comment by Luke616** [comment]
Having the same issue, same error log.

Happens to me but doesn't happen to my friend who is on the same VPN as I am. Also, another friend of mine has the issue and isn't on any VPN at all so I'm not sure that's the issue. We're all running Java 8 and using multiMC 0.5.0-945. I can send you logs and the files I'm working with if you want.

**Comment by kotoroshinoto** [comment]
I used a workaround
I created an update.bat:
"%1" -jar UpdaterUpdater.jar "[config-url]" "PackInfo.cfg" "." "PackUpdate.jar"
echo "ERROR LEVEL OF UPDATE SCRIPT: %ERRORLEVEL%"
exit /b 0

then set the instance to execute "$INST_MC_DIR\update.bat" "$INST_JAVA" as the pre-launch command instead, feeding the java path for the instance to the batch file and allowing it to substitute a zero return value

**Comment by kencinder** [comment]
I'm having the very same problem. I noticed the PackInfo.cfg that gets downloaded on first run only has the first line, in my case my configs...everything after that fails. On a second run without altering anything, things work as expected.

My workaround is just to supply that PackInfo.cfg with the 1 line in the exported instance, then whoever is importing it is basically doing a second run on it.

This thing is GREAT btw. I can't stand needing "Approval" for a private modpack on Curse or ATLauncher, and Technic's launcher is far too dumbed down and lacking in configureability.

**Comment by XDjackieXD** [comment]
that's some very interesting behaviour. one way to work around this would be to add an optional checksum to the start of the update config file although I'm still not sure why this happens.

@kencinder I started using mcupdater instead of packupdate. It's sadly not integrated into multimc but it has way more features than my little mess of java code here ^^

**Comment by kencinder** [comment]
I deleted my comment because I misinterpreted the issue, while reading something else...sorted mine out. Turns out you have to supply an instance with a `mods` and `config` folder or packupdate will fail to download either.

**Comment by XDjackieXD** [comment]
should this still be a relevant issue, please reopen
