### ISSUE TITLE
example folder missing

### ISSUE THREAD

**Issue by nonchip** [XDjackieXD/PackUpdate#25]
> You can find an example modpack in the folder "ExamplePack".

there's no such thing.

**Comment by Kilobyte22** [comment]
That information is actually left over from a refactor, which is still in progress. You have two options:
* Use Release [2.4](https://github.com/XDjackieXD/PackUpdate/releases/tag/2.4) - there you also have an ExamplePack
* Use the current development builds (3.x) - for that check the [wiki](https://github.com/XDjackieXD/PackUpdate/wiki).

The development builds are mostly stable, the only missing part is automatic upgrade from 2.x - once thats done it will be moved to production

For further questions, feel free to ask

**Comment by Kilobyte22** [comment]
I have updated the readme to point to the wiki.

**Comment by Kilobyte22** [comment]
Closing due to on inactivity
