### ISSUE TITLE
Problem with using to update server

### ISSUE THREAD

**Issue by kencinder** [XDjackieXD/PackUpdate#27]
I was using the previous version to also update my server, I love that you've added flags so I can now stick with just one config to handle both client and server, but it doesn't appear to work.

```This program is intended to run as MultiMC Pre-Launch Hook```

**Comment by Kilobyte22** [comment]
Ah, yes thats a known bug in the updater that i already fixed. I have not pushed the released update to GitHub, but you can grab a copy from https://ci.chaosfield.at/job/PackUpdate/job/PackUpdateUpdater/.

**Comment by kencinder** [comment]
Thanks latest build there is working fine on server.

**Comment by Kilobyte22** [comment]
That's what i wanted to hear, glad i could help you

**Comment by Kilobyte22** [comment]
For the record: The fixed version of PackUpdateUpdater is now available as 3.0.1
