### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by UndarkAido** [XDjackieXD/PackUpdate#28]
It would be awesome if this could support Fabric. [Jumploader](https://www.curseforge.com/minecraft/mc-mods/jumploader) might work as a workaround but I have yet to try it.

**Comment by comp500** [comment]
Not sure why it wouldn't work with Fabric mods, as MultiMC has full support for Fabric?
Edit: Or is this in relation to the server installer?

**Comment by UndarkAido** [comment]
I was looking at https://github.com/XDjackieXD/PackUpdate/wiki

> Currently supported are: mod, resources, config and forge

**Comment by comp500** [comment]
I think you can do https://github.com/XDjackieXD/PackUpdate/wiki#alternative-1-creating-the-minecraft-instance-manually then, and just not include forge in the pack CSV file.

**Comment by UndarkAido** [comment]
Oh, ok. Thanks!
