### ISSUE TITLE
PackUpdate doesn't follow curse redirects properly

### ISSUE THREAD

**Issue by comp500** [XDjackieXD/PackUpdate#9]
Curse provides redirects for download links to go to its CDN, so the download links do not work anymore with PackUpdate. The download function needs to be fixed to follow redirects. Below is a screenshot of the redirects that curse does when requesting an addon.
![curseredir](https://cloud.githubusercontent.com/assets/1138417/18607563/46387b56-7cc8-11e6-8673-c50affed721c.PNG)
PackUpdate seems to take the redirect the same as a 200 response (or it doesn't work with 307?) and therefore saves the addon as a 0kb file.
EDIT: This may also be because FileUtils doesn't follow redirects that change the protocol.
EDIT2: I changed the protocol to https, and it does seem to actually download the files, but not save them properly.

**Comment by XDjackieXD** [comment]
The problem is that the apache commons file downloader doesn't handle redirects at all. If I find some time tomorrow, I will switch to a normal implementation using a buffered reader which should handle redirects fine.

**Comment by XDjackieXD** [comment]
I replaced the apache commons downloader with my own downloading code which should correctly handle any redirects.

**Comment by comp500** [comment]
Thanks for the quick fix, it now works!
